"""Add scheduling and timer fields to Quiz

Revision ID: 7c505f9917d6
Revises: 7779a0828c9b
Create Date: 2025-10-04 11:26:41.093856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c505f9917d6'
down_revision = '7779a0828c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('bloom_level',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('opens_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closes_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('time_limit')
        batch_op.drop_column('closes_at')
        batch_op.drop_column('opens_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('bloom_level',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('question_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
