"""Add analysis_text to Quiz model

Revision ID: 9dea9da207b8
Revises: 4006aea74bf9
Create Date: 2025-08-20 16:15:36.808123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dea9da207b8'
down_revision = '4006aea74bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('analysis_text')

    # ### end Alembic commands ###
